#!/bin/sh
EOL_VERS="8.0 saas-6 9.0 saas-11.1 saas-11.2 saas-11.4 saas-11.5 "
VERSIONS="master saas-13 10.0 saas-14 saas-15 saas-16 saas-17 saas-18 11.0 saas-11.3 12.0 saas-12.1"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Colo

REP1="odoo;git@github.com:odoo/odoo.git;git@github.com:odoo-dev/odoo.git"
REP2="enterprise;git@github.com:odoo/enterprise.git;git@github.com:odoo-dev/enterprise.git"
REP3="design-themes;git@github.com:odoo/design-themes.git;git@github.com:odoo-dev/design-themes.git"

base_dir="/datas/src-migrations/"

for ver in $VERSIONS
do
    for repo in $REP1 $REP2 $REP3
    do
        dir="$(echo ${repo} | cut -d';' -f1)"
        rep="$(echo ${repo} | cut -d';' -f2)"
        repdev="$(echo ${repo} | cut -d';' -f3)"
        cd $base_dir
        if [ ! -d "$dir/$ver" ]; then
            echo "${RED}clone $dir ${BLUE}$ver${NC}"
            git clone --single-branch --branch $ver --depth 1 $rep $dir/$ver
        else
            echo "${GREEN}update $dir ${BLUE}$ver${NC}"
            cd $dir/$ver 
            git co $ver
            git fetch origin $ver
            git rebase --autostash
            git remote add dev $repdev
        fi
    done    
    echo "${GREEN}Finished.${NC}"
done
