#!/bin/bash
EOL_VERS="8.0 saas-6 9.0 saas-11 saas-12 saas-11.1 saas-11.2 saas-11.3 saas-11.4 saas-11.5 saas-12.1 saas-12.2 saas-12.4 saas-12.5 saas-13.2 saas-13.3 saas-13.4 saas-13.5"
VERSIONS="11.0 12.0 saas-12.3 13.0 14.0 master"

RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
NC='\e[39m' # No Colo

REP1="odoo;git@github.com:odoo/odoo.git;git@github.com:odoo-dev/odoo.git"
REP2="enterprise;git@github.com:odoo/enterprise.git;git@github.com:odoo-dev/enterprise.git"
REP3="design-themes;git@github.com:odoo/design-themes.git;git@github.com:odoo-dev/design-themes.git"

base_dir="/datas/src-migrations/"

for ver in $VERSIONS
do
    for repo in $REP1 $REP2 $REP3
    do
        dir="$(echo ${repo} | cut -d';' -f1)"
        rep="$(echo ${repo} | cut -d';' -f2)"
        repdev="$(echo ${repo} | cut -d';' -f3)"
        cd $base_dir
        if [ ! -d "$dir/$ver" ]; then
            echo -e "${RED}clone $dir ${BLUE}$ver${NC}"
            git clone --single-branch --branch $ver --depth 1 $rep $dir/$ver
        else
            echo -e "${GREEN}update $dir ${BLUE}$ver${NC}"
            cd $dir/$ver
            git co $ver
            git fetch origin $ver
	        git reset HEAD --hard
	        git clean -dfx
            git rebase --autostash
            git remote add dev $repdev
        fi
    done
    echo -e "${GREEN}Finished.${NC}"
done
