#!/bin/bash
if [ -z "$2" ]
  then
    echo "No argument supplied"
    echo "Usage = odoo-upgrade version db [template_db] [other_args]"
    exit 1
fi
cd "/datas/src-migrations/odoo/$1/"
ln -s /datas/src-migrations/saas-migration odoo/addons/base/maintenance
if [ ! -z "$3" ]
  then
    dropdb $2
    createdb $2 --template $3
fi
./odoo-bin --addons-path=/datas/src-migrations/enterprise/$1,/datas/src-migrations/odoo/$1/odoo/addons,/datas/src-migrations/odoo/$1/addons,/datas/src-migrations/design-themes/$1 -d $2 ${@:4} --db-filter=^$2$ -u all

