#!/bin/bash
START_VERSIONS="12.0 saas-12.3 saas-12.4"
TARGET="13.0"

RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
NC='\e[39m' # No Colo

REP1="odoo;git@github.com:odoo/odoo.git;addons"
REP2="enterprise;git@github.com:odoo/enterprise.git;."

base_dir="/datas/src-migrations/"

for ver in $START_VERSIONS
do
    for repo in $REP1 $REP2
    do
        dir="$(echo ${repo} | cut -d';' -f1)"
        rep="$(echo ${repo} | cut -d';' -f2)"
        addonsfolder="$(echo ${repo} | cut -d';' -f3)"
        cd "$base_dir/$dir/$ver"
        git co $ver
        git fetch origin $ver
        git rebase --autostash
        echo -e "${RED}$dir ${BLUE}$ver${NC}"
        cd $addonsfolder
        for d in */ ; do
            addon=${d%/}
            src_db=$ver-upddb-$addon
            trg_db=$TARGET-$ver-$addon
            if psql -lqt | cut -d \| -f 1 | grep -qw $src_db; then
                #DB already exists. Update module?
                echo -e "Existing DB ${RED}$dir ${BLUE}$ver ${NC}install module ${GREEN}$addon${NC}"
                odoo-launch $ver -d $src_db -u $addon --stop-after-init --logfile /dev/null
            else
                echo -e "Create DB ${RED}$dir ${BLUE}$ver ${NC}install module ${GREEN}$addon${NC}"
                odoo-launch $ver -d $src_db -i $addon --stop-after-init --logfile /dev/null
            fi
            dropdb $trg_db
            # odoo-upgrade $TARGET $trg_db $src_db --stop-after-init
        done
    done
    echo -e "${GREEN}Finished.${NC}"
done
