#! /bin/bash
#Switch odoo version
cd /datas/progs/enterprise && git co $1 && git pull && find . -name \*.pyc -delete
cd /datas/progs/design-themes && git co $1 && git pull && find . -name \*.pyc -delete
cd /datas/progs/odoo && git co $1 && git pull && find . -name \*.pyc -delete
cd /datas/progs/internal && git pull && find . -name \*.pyc -delete
